import './globals.css'


export const metadata = {
  title: 'Events',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-bg-primary'>{children}</body>
    </html>
  )
}
